sudo: false
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install git+https://github.com/uw-it-aca/mdot/#egg=mdot
  - pip install pep8
  - pip install coverage
  - pip install python-coveralls
  - pip install django_compressor
  - pip install django-templatetag-handlebars
  - pip install django-easy-pjax
before_script:
  - cp travis-ci/manage.py manage.py
  - python manage.py syncdb --noinput
script:
  - pep8 mdotdevs/ --exclude=migrations
  - coverage run --source=mdotdevs/ --omit=mdotdevs/migrations/* manage.py test mdotdevs
after_script:
  - coveralls
